// https://www.behindthename.com/api/appendix2.php
export const BEHIND_THE_NAME_USAGES = [
  {CODE: 'afk', FULL: 'Afrikaans', DESCRIPTION: 'Afrikaans names are used by Afrikaans speakers in the countries of South Africa and Namibia.'},
  {CODE: 'afr', FULL: 'African', DESCRIPTION: 'African names are used in various places on the continent of Africa.'},
  {CODE: 'aka', FULL: 'Akan', DESCRIPTION: 'Akan names are used by the Akan people of Ghana and Ivory Coast.'},
  {CODE: 'alb', FULL: 'Albanian', DESCRIPTION: '	Albanian names are used in the country of Albania, as well as Kosovo and other Albanian communities throughout the world.'},
  {CODE: 'ame', FULL: 'Native American', DESCRIPTION: 'These names are or were used by the various indigenous peoples who inhabited North and South America.'},
  {CODE: 'amh', FULL: 'Amharic', DESCRIPTION: '	Amharic names are used in Ethiopia.'},
  {CODE: 'anci', FULL: 'Ancient', DESCRIPTION: 'These names were used in various ancient regions.'},
  {CODE: 'apa', FULL: 'Apache', DESCRIPTION: 'Apache names are used by the Apache peoples of the southwestern United States.'},
  {CODE: 'ara', FULL: 'Arabic', DESCRIPTION: 'Arabic names are used in the Arab world, as well as some other regions within the larger Muslim world. They are not necessarily of Arabic origin, though most in fact are. Compare also Persian names and Turkish names.'},
  {CODE: 'arm', FULL: 'Armenian', DESCRIPTION: 'Armenian names are used in the country of Armenia in western Asia, as well as in Armenian diaspora communities throughout the world.'},
  {CODE: 'asm', FULL: 'Assamese', DESCRIPTION: 'Assamese names are used in Assam in eastern India.'},
  {CODE: 'astr', FULL: 'Astronomy', DESCRIPTION: 'These names occur primarily in astronomy. They are not commonly given to real people.'},
  {CODE: 'aus', FULL: 'Indigenous Australian', DESCRIPTION: '	Indigenous Australian names are used by the indigenous people of Australia (also called Aborigines).'},
  {CODE: 'aym	', FULL: 'Aymara', DESCRIPTION: 'Aymara names are used by the Aymara people of Bolivia and Peru.'},
  {CODE: 'aze', FULL: 'Azerbaijani', DESCRIPTION: '	Azerbaijani names are used by the Azeri people of Azerbaijan and northern Iran.'},
  {CODE: 'bal', FULL: 'Balinese', DESCRIPTION: 'Balinese names are used on the island of Bali, a part of Indonesia.'},
  {CODE: 'bas', FULL: 'Basque', DESCRIPTION: 'Basque names are used in the Basque Country (northern Spain and southern France).'},
  {CODE: 'bel', FULL: 'Belarusian', DESCRIPTION: 'Belarusian names are used in the country of Belarus in eastern Europe.'},
  {CODE: 'ben', FULL: 'Bengali', DESCRIPTION: 'Bengali names are used in Bangladesh and eastern India.'},
  {CODE: 'ber', FULL: 'Berber', DESCRIPTION: 'Berber names are used by the Berber (Amazigh) people of North Africa.'},
  {CODE: 'bhu', FULL: 'Bhutanese', DESCRIPTION: 'Bhutanese names are used in the country of Bhutan in southern Asia.'},
  {CODE: 'bibl', FULL: 'Biblical (All)', DESCRIPTION: 'These names occur in the Bible (in any language).'},
  {CODE: 'bos', FULL: 'Bosnian', DESCRIPTION: 'Bosnian names are used by the Bosniak people. For additional names, see Serbo-Croatian names, Arabic names and Turkish names.'},
  {CODE: 'bre', FULL: 'Breton', DESCRIPTION: 'Breton names are used in the region of Brittany in northwest France.'},
  {CODE: 'bsh', FULL: 'Bashkir', DESCRIPTION: 'Bashkir names are used in Bashkortostan in Russia.'},
  {CODE: 'bul', FULL: 'Bulgarian', DESCRIPTION: 'Bulgarian names are used in the country of Bulgaria in southeastern Europe.'},
  {CODE: 'cat', FULL: 'Catalan', DESCRIPTION: 'Catalan names are used in Catalonia in eastern Spain, as well as in other Catalan-speaking areas including Valencia, the Balearic Islands, and Andorra.'},
  {CODE: 'cela', FULL: 'Ancient Celtic', DESCRIPTION: ''},
  {CODE: 'celm', FULL: 'Celtic Mythology', DESCRIPTION: ''},
  {CODE: 'cew', FULL: 'Chewa', DESCRIPTION: 'Chewa names are used in Malawi, Mozambique and Zambia.'},
  {CODE: 'che', FULL: 'Chechen', DESCRIPTION: 'Chechen names are used in Chechnya, a federal subject of Russia.'},
  {CODE: 'chi', FULL: 'Chinese', DESCRIPTION: 'Chinese names are used in China and in Chinese communities throughout the world. Note that depending on the Chinese characters used these names can have many other meanings besides those listed here.'},
  {CODE: 'cht', FULL: 'Choctaw', DESCRIPTION: 'Choctaw names are used by the Choctaw people of Oklahoma and Mississippi.'},
  {CODE: 'cir', FULL: 'Circassian', DESCRIPTION: 'Circassian names are used in Circassia, part of the Caucasus region of Russia.'},
  {CODE: 'com', FULL: 'Comanche', DESCRIPTION: '	Comanche names are used by the Comanche people of the southern United States.'},
  {CODE: 'cop', FULL: 'Coptic', DESCRIPTION: 'These names are used by Coptic Christians in Egypt.'},
  {CODE: 'cor', FULL: 'Cornish', DESCRIPTION: 'Cornish names were used in southwest England in the region around Cornwall.'},
  {CODE: 'cre', FULL: 'Cree', DESCRIPTION: 'Cree names are used by the Cree people of Canada.'},
  {CODE: 'cro', FULL: 'Croatian', DESCRIPTION: 'Croatian names are used in the country of Croatia and other Croatian communities throughout the world.'},
  {CODE: 'crs', FULL: 'Corsican', DESCRIPTION: 'Corsican names are used on the island of Corsica.'},
  {CODE: 'cze', FULL: 'Czech', DESCRIPTION: 'Czech names are used in the Czech Republic in central Europe.'},
  {CODE: 'dan', FULL: 'Danish', DESCRIPTION: 'Danish names are used in the country of Denmark in northern Europe.'},
  {CODE: 'dgs', FULL: 'Dagestani', DESCRIPTION: 'Dagestani names are used in Dagestan, a federal subject of Russia.'},
  {CODE: 'dut', FULL: 'Dutch', DESCRIPTION: 'Dutch names are used in the Netherlands and Flanders.'},
  {CODE: 'eng', FULL: 'English', DESCRIPTION: 'English names are used in English-speaking countries.'},
  //{CODE: 'enga', FULL: '', DESCRIPTION: ''},
  {CODE: 'esp', FULL: 'Esperanto', DESCRIPTION: 'Esperanto names are used by speakers of the planned language Esperanto.'},
  {CODE: 'est', FULL: 'Estonian', DESCRIPTION: 'Estonian names are used in the country of Estonia in northern Europe.'},
  {CODE: 'eth', FULL: 'Ethiopian', DESCRIPTION: 'Ethiopian names are used in the country of Ethiopia in eastern Africa.'},
  {CODE: 'ewe', FULL: 'Ewe', DESCRIPTION: 'Ewe names are used by the Ewe people of Ghana and Togo.'},
  {CODE: 'fae', FULL: 'Faroese', DESCRIPTION: 'Faroese names are used on the Faroe Islands.'},
  {CODE: 'fairy', FULL: 'Fairy', DESCRIPTION: 'Fun category'},
  {CODE: 'fil', FULL: 'Filipino', DESCRIPTION: 'Filipino names are used on the island nation of the Philippines.'},
  {CODE: 'fin', FULL: 'Finnish', DESCRIPTION: 'Finnish names are used in the country of Finland in northern Europe.'},
  {CODE: 'fle', FULL: 'Flemish', DESCRIPTION: 'Flemish names are used in Flanders (the northern half of Belgium where Dutch is spoken).'},
  {CODE: 'fntsg', FULL: 'Gluttakh', DESCRIPTION: 'Fantasy category'},
  {CODE: 'fntsm', FULL: 'Monstrall', DESCRIPTION: 'Fantasy category'},
  {CODE: 'fntsr', FULL: 'Romanto', DESCRIPTION: 'Fantasy category'},
  {CODE: 'fntss', FULL: 'Simitiq', DESCRIPTION: 'Fantasy category'},
  {CODE: 'fntst', FULL: 'Tsang', DESCRIPTION: 'Fantasy category'},
  {CODE: 'fntsx', FULL: 'Xalaxxi', DESCRIPTION: 'Fantasy category'},
  {CODE: 'fntsy', FULL: 'Fantasy', DESCRIPTION: 'Fantasy category'},
  {CODE: 'fre', FULL: 'French', DESCRIPTION: 'French names are used in France and other French-speaking regions.'},
  {CODE: 'fri', FULL: 'Frisian', DESCRIPTION: 'Frisian names are used in Friesland in the northern Netherlands and in East and North Frisia in northwestern Germany.'},
  {CODE: 'gal', FULL: 'Galician', DESCRIPTION: 'Galician names are used in Galicia in northwestern Spain.'},
  {CODE: 'gan', FULL: 'Ganda', DESCRIPTION: 'Ganda names are used by the Ganda people of Uganda.'},
  {CODE: 'geo', FULL: 'Georgian', DESCRIPTION: 'Georgian names are used in the country of Georgia in central Eurasia.'},
  {CODE: 'ger', FULL: 'German', DESCRIPTION: 'German names are used in Germany and other German-speaking areas such as Austria and Switzerland.'},
  //{CODE: 'gmca', FULL: '', DESCRIPTION: ''},
  {CODE: 'goth', FULL: 'Goth', DESCRIPTION: 'Fun category'},
  {CODE: 'gre', FULL: 'Greek', DESCRIPTION: 'Greek names are used in the country of Greece and other Greek-speaking communities throughout the world.'},
  {CODE: 'grea', FULL: 'Ancient Greek', DESCRIPTION: ''},
  {CODE: 'grem', FULL: 'Greek Mythology', DESCRIPTION: ''},
  {CODE: 'Greek Mythology', FULL: 'Greenlandic', DESCRIPTION: 'Greenlandic names are used by the indigenous people of Greenland.'},
  {CODE: 'guj', FULL: 'Gujarati', DESCRIPTION: 'Gujarati names are used in western India (in the state of Gujarat).'},
  {CODE: 'haw', FULL: 'Hawaiian', DESCRIPTION: 'Hawaiian names are used by the indigenous people of Hawaii.'},
  {CODE: 'hil', FULL: 'Hiligaynon', DESCRIPTION: 'Hiligaynon names are used in the Philippines.'},
  {CODE: 'hin', FULL: 'Hindi', DESCRIPTION: 'Hindi names are used in northern India.'},
  {CODE: 'hippy', FULL: 'Hippy', DESCRIPTION: 'Fun category'},
  {CODE: 'hist', FULL: 'History', DESCRIPTION: 'These names are used primarily to refer to historical persons. They are not commonly used by other people.'},
  {CODE: 'hmo', FULL: 'Hmong', DESCRIPTION: 'Hmong names are used by the Hmong people in southeastern Asia.'},
  {CODE: 'hun', FULL: 'Hungarian', DESCRIPTION: 'Hungarian names are used in the country of Hungary in central Europe.'},
  {CODE: 'ibi', FULL: 'Ibibio', DESCRIPTION: 'Ibibio names are used by the Ibibio people of Nigeria.'},
  {CODE: 'ice', FULL: 'Icelandic', DESCRIPTION: 'Igbo names are used by the Igbo people of Nigeria.'},
  {CODE: 'ind', FULL: 'Indian', DESCRIPTION: 'Indian names are used in India and in Indian communities throughout the world.'},
  {CODE: 'indm', FULL: 'Indian Mythology', DESCRIPTION: ''},
  {CODE: 'ing', FULL: 'Ingush', DESCRIPTION: 'Ingush names are used in Ingushetia, a federal subject of Russia.'},
  {CODE: 'ins', FULL: 'Indonesian', DESCRIPTION: 'Indonesian names are used on the island nation of Indonesia in southeast Asia.'},
  {CODE: 'inu', FULL: 'Inuit', DESCRIPTION: 'Inuit names are used by the Inuit people of the North American Arctic.'},
  {CODE: 'ira', FULL: 'Iranian', DESCRIPTION: 'Iranian names are used in the country of Iran in southwestern Asia.'},
  {CODE: 'iri', FULL: 'Irish', DESCRIPTION: 'Irish names are used on the island of Ireland as well as elsewhere in the Western World as a result of the Irish diaspora.'},
  {CODE: 'iro', FULL: 'Iroquois', DESCRIPTION: 'Iroquois names are used by the Iroquois people of the United States and Canada.'},
  {CODE: 'ita', FULL: 'Italian', DESCRIPTION: 'Italian names are used in Italy and other Italian-speaking regions such as southern Switzerland.'},
  {CODE: 'jap', FULL: 'Japanese', DESCRIPTION: 'Japanese names are used in Japan and in Japanese communities throughout the world. Note that depending on the Japanese characters used these names can have many other meanings besides those listed here.'},
  {CODE: 'jav', FULL: 'Javanese', DESCRIPTION: 'Javanese names are used on the island of Java, a part of Indonesia.'},
  {CODE: 'jer', FULL: 'Jèrriais', DESCRIPTION: 'Jèrriais names are used on the island of Jersey between Britain and France.'},
  {CODE: 'jew', FULL: 'Jewish', DESCRIPTION: 'These names are used by Jews. For more specific lists, see Hebrew names and Yiddish names.'},
  {CODE: 'kan', FULL: 'Kannada', DESCRIPTION: 'Kannada names are used in western India.'},
  {CODE: 'kaz', FULL: 'Kazakh', DESCRIPTION: '	Kazakh names are used in the country of Kazakhstan in central Eurasia.'},
  {CODE: 'khm', FULL: 'Khmer', DESCRIPTION: 'Khmer names are used in the country of Cambodia in southeastern Asia.'},
  {CODE: 'kik', FULL: 'Kikuyu', DESCRIPTION: 'Kikuyu names are used by the Kikuyu people of Kenya.'},
  {CODE: 'kk', FULL: 'Kreatyve', DESCRIPTION: 'Fun category'},
  {CODE: 'kor', FULL: 'Korean', DESCRIPTION: 'Korean names are used in South and North Korea. Note that depending on the Korean characters used these names can have many other meanings besides those listed here.'},
  {CODE: 'kur', FULL: 'Kurdish', DESCRIPTION: 'Kurdish names are used by the Kurdish people of the Middle East.'},
  {CODE: 'kyr', FULL: 'Kyrgyz', DESCRIPTION: 'Kyrgyz names are used in the country of Kyrgyzstan in central Eurasia.'},
  {CODE: 'lat', FULL: 'Latvian', DESCRIPTION: 'Latvian names are used in the country of Latvia in northern Europe.'},
  {CODE: 'lim', FULL: 'Limburgish', DESCRIPTION: 'Limburgish names are used in the Limburg region, which straddles the border between Belgium, the Netherlands and Germany.	'},
  {CODE: 'lite', FULL: 'Literature', DESCRIPTION: 'These names occur primarily in literature. They are not commonly given to real people.'},
  {CODE: 'lth', FULL: 'Lithuanian', DESCRIPTION: 'Lithuanian names are used in the country of Lithuania in northern Europe.'},
  {CODE: 'luh', FULL: 'Luhya', DESCRIPTION: 'Luhya names are used by the Luhya people of western Kenya.'},
  {CODE: 'luo', FULL: 'Luo', DESCRIPTION: 'Luo names are used by the Luo people of Kenya.'},
  {CODE: 'mac', FULL: 'Macedonian', DESCRIPTION: 'Macedonian names are used in the country of Macedonia (FYROM) in southeastern Europe.'},
  {CODE: 'mal', FULL: 'Maltese', DESCRIPTION: 'Maltese names are used on the island of Malta.'},
  {CODE: 'man', FULL: 'Manx', DESCRIPTION: 'Manx names are used on the Isle of Man.'},
  {CODE: 'mao', FULL: 'Maori', DESCRIPTION: 'Maori names are used by the indigenous people of New Zealand, the Maori.'},
  {CODE: 'map', FULL: 'Mapuche', DESCRIPTION: 'Mapuche names are used by the Mapuche people of Chile and Argentina.'},
  {CODE: 'may', FULL: 'Mayan', DESCRIPTION: 'Mayan names are used by the Maya people of Mexico and Central America.'},
  {CODE: 'medi', FULL: 'Medieval', DESCRIPTION: 'These names were used in medieval times.'},
  {CODE: 'mlm', FULL: 'Malayalam', DESCRIPTION: 'Malayalam names are used in southern India.'},
  {CODE: 'mly', FULL: 'Malay', DESCRIPTION: 'Malay names are used in Malaysia, Indonesia, Brunei, Singapore, and Thailand.'},
  {CODE: 'mon', FULL: 'Mongolian', DESCRIPTION: 'Mongolian names are used in the country of Mongolia in central Asia.'},
  {CODE: 'morm', FULL: 'Mormon', DESCRIPTION: 'Mormon names occur in the Book of Mormon.'},
  {CODE: 'mrt', FULL: 'Marathi', DESCRIPTION: 'Marathi names are used by the Marathi people in western India.'},
  {CODE: 'mwe', FULL: 'Mwera', DESCRIPTION: 'Mwera names are used by the Mwera people of Tanzania.'},
  {CODE: 'myth', FULL: 'Mythology', DESCRIPTION: 'These names occur in mythology and religion.'},
  {CODE: 'nah', FULL: 'Nahuatl', DESCRIPTION: 'Nahuatl names are used by the Nahua peoples of Mexico and Central America.'},
  {CODE: 'nav', FULL: 'Navajo', DESCRIPTION: 'Navajo names are used by the Navajo people of the southwestern United States.'},
  {CODE: 'nde', FULL: 'Ndebele', DESCRIPTION: 'Ndebele names are used by the Ndebele people of South Africa and Zimbabwe.'},
  {CODE: 'nep', FULL: 'Nepali', DESCRIPTION: 'Nepali names are used in the country of Nepal in southern Asia.'},
  {CODE: 'nor', FULL: 'Norwegian', DESCRIPTION: 'Norwegian names are used in the country of Norway in northern Europe.'},
  {CODE: 'nrm', FULL: 'Norman', DESCRIPTION: 'Norwegian names are used in the country of Norway in northern Europe.'},
  {CODE: 'nuu', FULL: 'Nuu-chah-nulth', DESCRIPTION: 'Nuu-chah-nulth names are used on Vancouver Island, Canada.'},
  {CODE: 'occ', FULL: 'Occitan', DESCRIPTION: 'Occitan names are used in southern France and parts of Spain and Italy.'},
  {CODE: 'odi', FULL: 'Odia', DESCRIPTION: 'Odia or Oriya names are used in eastern India (in the state of Odisha).'},
  {CODE: 'oji', FULL: 'Ojibwe', DESCRIPTION: 'Ojibwe names are used by the Ojibwe people of Canada and the United States.'},
  {CODE: 'oss', FULL: 'Ossetian', DESCRIPTION: 'Ossetian names are used in Ossetia, which is a region split by Russia and Georgia.'},
  {CODE: 'pas', FULL: 'Pashto', DESCRIPTION: 'Pashto names are used in Afghanistan and northwestern Pakistan.'},
  {CODE: 'pcd', FULL: 'Picard', DESCRIPTION: 'Picard names are used in northern France.'},
  {CODE: 'per', FULL: 'Persian', DESCRIPTION: 'Persian names are used in the country of Iran, in southwestern Asia, which is part of the Muslim world.'},
  {CODE: 'pets', FULL: 'Pet', DESCRIPTION: 'These names are most commonly given to pets: dogs, cats, etc.'},
  {CODE: 'pol', FULL: 'Polish', DESCRIPTION: 'Polish names are used in the country of Poland in central Europe.'},
  {CODE: 'popu', FULL: 'Popular Culture', DESCRIPTION: 'These names occur primarily in popular culture and entertainment. They are not commonly given to real people.'},
  {CODE: 'por', FULL: 'Portuguese', DESCRIPTION: 'Portuguese names are used in Portugal, Brazil and other Portuguese-speaking areas.'},
  {CODE: 'pun', FULL: 'Punjabi', DESCRIPTION: 'Punjabi names are used in the Punjab region of India and Pakistan.'},
  {CODE: 'que', FULL: 'Quechua', DESCRIPTION: 'Quechua names are used by the Quechua people of South America.'},
  {CODE: 'rap', FULL: 'Rapper', DESCRIPTION: 'Fun category'},
  {CODE: 'rmn', FULL: 'Romanian', DESCRIPTION: 'Romanian names are used in the countries of Romania and Moldova in eastern Europe.	'},
  {CODE: 'roma', FULL: 'Ancient Roman	', DESCRIPTION: ''},
  {CODE: 'romm', FULL: 'Roman Mythology	', DESCRIPTION: ''},
  {CODE: 'rus', FULL: 'Russian', DESCRIPTION: 'Russian names are used in the country of Russia and in Russian-speaking communities throughout the world.'},
  {CODE: 'sam', FULL: 'Sami', DESCRIPTION: 'Sami names are used by the Sami people who inhabit northern Scandinavia.'},
  {CODE: 'sax', FULL: 'Low German', DESCRIPTION: 'Low German'},
  {CODE: 'sca', FULL: 'Scandinavian', DESCRIPTION: 'Scandinavian names are used in the Scandinavia region of northern Europe. For more specific lists, see Swedish names, Danish names and Norwegian names.'},
  //{CODE: 'scaa', FULL: '', DESCRIPTION: ''},
  {CODE: 'scam', FULL: 'Norse Mythology', DESCRIPTION: ''},
  {CODE: 'sco', FULL: 'Scottish', DESCRIPTION: 'Scottish names are used in the country of Scotland as well as elsewhere in the Western World as a result of the Scottish diaspora.'},
  {CODE: 'sct', FULL: 'Scots', DESCRIPTION: 'Scots names are used by speakers of the Scots language.'},
  {CODE: 'ser', FULL: 'Serbian', DESCRIPTION: 'Serbian names are used in the country of Serbia in southeastern Europe.'},
  {CODE: 'sha', FULL: 'Shawnee', DESCRIPTION: 'Shawnee names are used by the Shawnee people of Oklahoma.'},
  {CODE: 'sho', FULL: 'Shona', DESCRIPTION: 'Shona names are used by the Shona people of Zimbabwe.'},
  {CODE: 'sic', FULL: 'Sicilian', DESCRIPTION: 'These names are a subset of Italian names used more often by speakers of Sicilian. Listed separately are Italian names.'},
  {CODE: 'sio', FULL: 'Sioux', DESCRIPTION: 'Sioux names are used by the Sioux people of the central United States and Canada.	'},
  {CODE: 'slam', FULL: 'Norse Mythology', DESCRIPTION: ''},
  {CODE: 'slk', FULL: 'Slovak', DESCRIPTION: 'Slovak names are used in the country of Slovakia in central Europe.'},
  {CODE: 'sln', FULL: 'Slovene', DESCRIPTION: 'Slovene names are used in the country of Slovenia in central Europe.'},
  {CODE: 'sor', FULL: 'Sorbian', DESCRIPTION: 'Sorbian names are used in Lusatia in eastern Germany.'},
  {CODE: 'sot', FULL: 'Sotho', DESCRIPTION: 'Sotho names are used by the Sotho people of Lesotho and South Africa.'},
  {CODE: 'spa', FULL: 'Spanish', DESCRIPTION: 'Spanish names are used in Spain and other Spanish-speaking countries (such as those in South America).'},
  {CODE: 'swa', FULL: 'Swahili', DESCRIPTION: 'Swahili names are used by Swahili speakers in eastern Africa.'},
  {CODE: 'swe', FULL: 'Swedish', DESCRIPTION: 'Swedish names are used in the country of Sweden in northern Europe.'},
  {CODE: 'tag', FULL: 'Tagalog', DESCRIPTION: 'Tagalog names are used in the Philippines.'},
  {CODE: 'tah', FULL: 'Tahitian', DESCRIPTION: 'Tahitian names are used in French Polynesia (part of which is the island of Tahiti).'},
  {CODE: 'taj', FULL: 'Tajik', DESCRIPTION: 'Tajik names are used in the country of Tajikistan in central Asia.'},
  {CODE: 'tam', FULL: 'Tamil', DESCRIPTION: 'Tamil names are used in southern India and Sri Lanka.'},
  {CODE: 'tat', FULL: 'Tatar', DESCRIPTION: 'Tatar names are used in Tatarstan in Russia.'},
  {CODE: 'tel', FULL: 'Telugu', DESCRIPTION: 'Telugu names are used in eastern India.'},
  {CODE: 'tha', FULL: 'Thai', DESCRIPTION: 'Thai names are used in the country of Thailand in southeastern Asia.'},
  {CODE: 'theo', FULL: 'Theology', DESCRIPTION: 'These names are used to refer to (Judeo-Christian-Islamic) deities. They are not bestowed upon real people.'},
  {CODE: 'tib', FULL: 'Tibetan', DESCRIPTION: 'Tibetan names are used by the Tibetan people who live in the region of Tibet in central Asia.'},
  {CODE: 'tkm', FULL: 'Turkmen', DESCRIPTION: 'Turkmen names are used in the country of Turkmenistan.'},
  {CODE: 'trans', FULL: 'Transformer', DESCRIPTION: 'Fun category'},
  {CODE: 'tsw', FULL: 'Tswana', DESCRIPTION: 'Tswana names are used in Botswana.'},
  {CODE: 'tum', FULL: 'Tumbuka', DESCRIPTION: 'Tumbuka names are used in Malawi, Zambia and Tanzania.'},
  {CODE: 'tup', FULL: 'Tupí', DESCRIPTION: 'Tupí names are used by the Tupí people of Brazil.'},
  {CODE: 'tur', FULL: 'tur', DESCRIPTION: 'Turkish names are used in the country of Turkey, which is situated in western Asia and southeastern Europe. Turkey is part of the larger Muslim world.'},
  {CODE: 'ukr', FULL: 'Ukrainian', DESCRIPTION: 'Ukrainian names are used in the country of Ukraine in eastern Europe.'},
  {CODE: 'urd', FULL: 'Urdu', DESCRIPTION: 'Urdu names are used in Pakistan and India.'},
  {CODE: 'urh', FULL: 'Urhobo', DESCRIPTION: 'Urhobo names are used by the Urhobo people of Nigeria.'},
  {CODE: 'usa', FULL: 'American', DESCRIPTION: 'American names are used in the United States.'},
  {CODE: 'uyg', FULL: 'uyg', DESCRIPTION: 'Uyghur names are used by the Uyghur people in western China.'},
  {CODE: 'uzb', FULL: 'Uzbek', DESCRIPTION: 'Uzbek names are used in the country of Uzbekistan in central Asia.'},
  {CODE: 'vari', FULL: 'Various', DESCRIPTION: 'These names do not "belong" to any one culture. They are put here because they cannot be categorized anywhere else.'},
  {CODE: 'vie', FULL: 'Vietnamese', DESCRIPTION: 'Vietnamese names are used in the country of Vietnam in southeastern Asia.'},
  {CODE: 'wel', FULL: 'Welsh', DESCRIPTION: 'Welsh names are used in the country of Wales in Britain.'},
  {CODE: 'witch', FULL: 'Witch', DESCRIPTION: 'Fun category'},
  {CODE: 'wrest', FULL: 'Wrestler', DESCRIPTION: 'Fun category'},
  {CODE: 'xho', FULL: 'Xhosa', DESCRIPTION: 'Xhosa names are used by the Xhosa people of South Africa.'},
  {CODE: 'yao', FULL: 'Yao', DESCRIPTION: 'Yao names are used in Malawi, Tanzania and Mozambique.'},
  {CODE: 'yor', FULL: 'Yoruba', DESCRIPTION: 'Yoruba names are used by the Yoruba people of Nigeria.'},
  {CODE: 'zap', FULL: 'Zapotec', DESCRIPTION: 'Zapotec names are used by the Zapotec people of southern Mexico.'},
  {CODE: 'zul', FULL: 'Zulu', DESCRIPTION: 'Zulu'},
]
